# Generated by Django 3.2.4 on 2021-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255, verbose_name='functions')),
                ('points', models.JSONField(null=True, verbose_name='points')),
                ('interval', models.IntegerField(default=7, verbose_name='interval')),
                ('step', models.IntegerField(default=2, verbose_name='step')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='crated')),
                ('date_processed', models.DateTimeField(null=True, verbose_name='processed')),
            ],
        ),
    ]
